# This is a basic workflow to help you get started with Actions

name: Build and Deploy Master

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Testing Deployment'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      react-app-dir: ./tenant-file/portal-app
      api-dir: ./TenantFile/Api

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info    
      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm ci
      working-directory: ${{env.react-app-dir}}
      
    - name: Build the React App
      run: npm run build
      working-directory: ${{env.react-app-dir}}
      
    - name: Submit API to build
      run: gcloud builds submit --tag gcr.io/tenant-file-fc6de/tenant-file-api
      working-directory: ${{env.api-dir}}
    
    - name: Deploy API
      run: gcloud run deploy tenant-file-api --image gcr.io/tenant-file-fc6de/tenant-file-api --platform managed --region=us-central1
      working-directory: ${{env.api-dir}}

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: ./tenant-file

    
